# pylint: disable=too-many-lines
from dataclasses import dataclass
from datetime import datetime, date
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel

""" This class is autogenerated """


class m_AccessLevels(str, Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class m_StorageStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    DELETED = "DELETED"
    NEVER_EXISTED = "NEVER_EXISTED"


class m_AccountType(str, Enum):
    ASSET = "ASSET"
    EXPENSE = "EXPENSE"
    INCOME = "INCOME"
    EQUITY = "EQUITY"
    LIABILITY = "LIABILITY"
    DIVIDEND = "DIVIDEND"
    INCOME_SUMMARY = "INCOME_SUMMARY"


class m_AccountActions(str, Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class m_Person(BaseModel):
    id: Optional[UUID] = None
    created_on: Optional[datetime] = None
    created_by: Optional[str] = None
    email: str
    hashed_password: Optional[str] = None
    first_name: str
    last_name: str
    level: Optional[m_AccessLevels] = None
    active: Optional[bool] = None
    confirmed: Optional[bool] = None


class m_Entity(BaseModel):
    id: Optional[UUID] = None
    created_on: Optional[datetime] = None
    created_by: Optional[str] = None
    name: str


class m_PersonEntityJunction(BaseModel):
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    entity_id: Optional[UUID] = None


class m_Account(BaseModel):
    id: Optional[UUID] = None
    created_on: Optional[datetime] = None
    created_by: Optional[str] = None
    entity_id: Optional[UUID] = None
    name: str
    parent_account_id: Optional[UUID] = None
    type: m_AccountType
    archived: Optional[bool] = None


class m_Journal(BaseModel):
    id: Optional[UUID] = None
    created_on: Optional[datetime] = None
    timestamp: date
    created_by: Optional[UUID] = None
    entity_id: Optional[UUID] = None
    description: str
    closing_entry: Optional[bool] = None
    receipt_status: Optional[m_StorageStatus] = None


class m_Ledger(BaseModel):
    id: Optional[UUID] = None
    created_on: Optional[datetime] = None
    created_by: Optional[str] = None
    journal_id: UUID
    account_id: UUID
    amount: float
    direction: m_AccountActions
    reconciled: Optional[bool] = None


class m_Prepaid(BaseModel):
    id: Optional[UUID] = None
    created_on: Optional[datetime] = None
    created_by: Optional[str] = None
    amount: float
    receive_month: date
    processed: Optional[bool] = None
    original_journal_id: Optional[UUID] = None
    asset_account_id: UUID
    expense_account_id: UUID
    asset_account_type: m_AccountType
    expense_account_type: m_AccountType


@dataclass(frozen=True)
class c_AccessLevels:
    ADMIN = "ADMIN"
    USER = "USER"


@dataclass(frozen=True)
class c_StorageStatus:
    AVAILABLE = "AVAILABLE"
    DELETED = "DELETED"
    NEVER_EXISTED = "NEVER_EXISTED"


@dataclass(frozen=True)
class c_AccountType:
    ASSET = "ASSET"
    EXPENSE = "EXPENSE"
    INCOME = "INCOME"
    EQUITY = "EQUITY"
    LIABILITY = "LIABILITY"
    DIVIDEND = "DIVIDEND"
    INCOME_SUMMARY = "INCOME_SUMMARY"


@dataclass(frozen=True)
class c_AccountActions:
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


@dataclass(frozen=True)
class c_Person:
    id = "person.id"
    created_on = "person.created_on"
    created_by = "person.created_by"
    email = "person.email"
    hashed_password = "person.hashed_password"
    first_name = "person.first_name"
    last_name = "person.last_name"
    level = "person.level"
    active = "person.active"
    confirmed = "person.confirmed"


@dataclass(frozen=True)
class c_Entity:
    id = "entity.id"
    created_on = "entity.created_on"
    created_by = "entity.created_by"
    name = "entity.name"


@dataclass(frozen=True)
class c_PersonEntityJunction:
    id = "person_entity_junction.id"
    user_id = "person_entity_junction.user_id"
    entity_id = "person_entity_junction.entity_id"


@dataclass(frozen=True)
class c_Account:
    id = "account.id"
    created_on = "account.created_on"
    created_by = "account.created_by"
    entity_id = "account.entity_id"
    name = "account.name"
    parent_account_id = "account.parent_account_id"
    type = "account.type"
    archived = "account.archived"


@dataclass(frozen=True)
class c_Journal:
    id = "journal.id"
    created_on = "journal.created_on"
    timestamp = "journal.timestamp"
    created_by = "journal.created_by"
    entity_id = "journal.entity_id"
    description = "journal.description"
    closing_entry = "journal.closing_entry"
    receipt_status = "journal.receipt_status"


@dataclass(frozen=True)
class c_Ledger:
    id = "ledger.id"
    created_on = "ledger.created_on"
    created_by = "ledger.created_by"
    journal_id = "ledger.journal_id"
    account_id = "ledger.account_id"
    amount = "ledger.amount"
    direction = "ledger.direction"
    reconciled = "ledger.reconciled"


@dataclass(frozen=True)
class c_Prepaid:
    id = "prepaid.id"
    created_on = "prepaid.created_on"
    created_by = "prepaid.created_by"
    amount = "prepaid.amount"
    receive_month = "prepaid.receive_month"
    processed = "prepaid.processed"
    original_journal_id = "prepaid.original_journal_id"
    asset_account_id = "prepaid.asset_account_id"
    expense_account_id = "prepaid.expense_account_id"
    asset_account_type = "prepaid.asset_account_type"
    expense_account_type = "prepaid.expense_account_type"
